# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Triggers
trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# Steps
steps:

- script: echo Hello, ICT DevOps!
  displayName: 'Run a one-line script'

- script: |
    echo Let us add more tasks to build, test, and deploy our project.
    echo Learn more about YAML!
  displayName: 'Run a multi-line script'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'talaaabndeh@40.121.36.196'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    overwrite: false
    failOnEmptySource: true